### ISSUE TITLE
Command line option for enabling venv auto-activation

### ISSUE THREAD

**Issue by cj-wong** [mise-plugins/mise-poetry#15]
From this section: https://github.com/mise-plugins/mise-poetry?tab=readme-ov-file#virtualenv-activation

Is there a way to set this using `mise use`? I've looked at the docs and didn't find anything relevant. I'd love for there to be an easy way to enable this option (if it doesn't exist), without needing to use a TOML library.

**Comment by jdx** [comment]
No, I think this has been brought up before but not sure where. It would be good to add but because `mise use` takes multiple tools it might be tricky to get the options to work right.

If someone wants to play with clap and figure out a good way to present it, this wouldn't be that hard to add. I think clap would be the most challenging portion.

(cc @roele who tends to be good with these sort of challenges 🙃)

**Comment by roele** [comment]
@jdx you mentioned this in https://github.com/jdx/mise/issues/2309

**Comment by cj-wong** [comment]
Thanks for the response. I'll go ahead and close this in favor of the original issue.
